#my_string=input("меня зовут светлана")
print("меня зовут светлана".upper())
print("меня зовут Светлана".lower())
print("Меня Зовут Светлана".replace(" ",""))
my_string=("Меня зовут светлана")
print(my_string[0])
print(my_string[18])